name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - name: Set Git User
        run: |
          git config --global user.name "kirby-CI"
          git config --global user.email "kirby@kirby-motion-ci.com"

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Unplugged Packages
        run: yarn install --immutable --immutable-cache

      - name: Build
        run: yarn build:package
          
      - name: Create Release Pull Request
        uses: cometkim/yarn-changeset-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
